---
- hosts: production
  tasks:
  - name: Create backup of systemd unit file with fixed name
    copy:
      src: ~/.config/systemd/user/hashworksNET.service
      dest: ~/.config/systemd/user/hashworksNET.service.bak
      remote_src: yes
      mode: 0600

  - name: Copy systemd unit file
    copy:
      src: ../systemd/hashworksNET.service
      dest: ~/.config/systemd/user/hashworksNET.service
      mode: 0600

  - name: Create backup of binary file with fixed name
    copy:
      src: ~/bin/hashworksNET
      dest: ~/bin/hashworksNET.bak
      remote_src: yes
      mode: 0770

  - name: Copy binary
    copy:
      src: ../bin/hashworksNET
      dest: ~/bin/hashworksNET
      mode: 0770

  - name: Restart systemd service
    systemd:
      name: hashworksNET
      scope: user
      daemon_reload: true
      state: restarted
