---
- hosts: "{{remote_server}}"
  remote_user: "{{remote_user}}"

  tasks:
  - name: Copy systemd unit backup file
    copy:
      src: ~/.config/systemd/user/hashworksNET.service.bak
      dest: ~/.config/systemd/user/hashworksNET.service
      remote_src: yes
      mode: 0600

  - name: Copy binary backup file
    copy:
      src: ~/bin/hashworksNET.bak
      dest: ~/bin/hashworksNET
      remote_src: yes
      mode: 0775

  - name: Restart systemd service
    systemd:
      name: hashworksNET
      scope: user
      daemon_reload: true
      state: restarted
